### ISSUE TITLE
Python 3 intégration

### ISSUE THREAD

**Issue by sebburon** [doobix/csgo-c4-hue#2]
Your code is amazing i was trying to update it so it could run on python 3 but can't get around this error
TypeError: the JSON object must be str, not 'bytes'

**Comment by doobix** [comment]
i haven't messed with python 3 yet, but i did some googling...

in `csgo-c4-hue-server.py`, this line:

```
json_data = json.loads(request.data)
```

probably needs to be changed to this:

```
json_data = json.loads(request.data.decode())
```

or to this:

```
json_data = json.loads(request.data.decode('utf-8'))
```

**Comment by sebburon** [comment]
i'll try and keep you posted !

**Comment by sebburon** [comment]
Now fully working with python 3 !

**Comment by doobix** [comment]
awesome, good job!
